### ISSUE TITLE
error in compiling with Cython

### ISSUE THREAD

**Issue by Cogito2012** [YadiraF/face3d#10]
I encountered the error related to the [line349 in mesh_core.cpp](https://github.com/YadiraF/face3d/blob/2fc26906d159a11398cd3e7a9b3f16b6f8937da3/face3d/mesh/cython/mesh_core.cpp#L349)

`mesh_core.cpp:349:31: error: no matching function for call to 'std::basic_ofstream<char>::basic_ofstream(std::string&)'`

After I changed the line to:

`ofstream obj_file(filename.c_str());`

The problem can be solved.

**Comment by tensorboy** [comment]
Hi, @Cogito2012, I have the same question with you, did you find the solution about it?

**Comment by Cogito2012** [comment]
@tensorboy, Just change the line 349 in file mesh_core.cpp as I have mentioned above.

**Comment by tensorboy** [comment]
Thanks!

**Comment by kylemcdonald** [comment]
I had the same problem, and the suggested change fixed it for me.
