### ISSUE TITLE
error: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by welbeckzhou** [YadiraF/face3d#57]
When Compile c++ files to .so for python use:

python setup.py build_ext -i
the error occurs.

I use python 3.6, and the default gcc version in my anaconda env is 7.3.0

mesh_core.cpp:349:31: error: no matching function for call to ‘std::basic_ofstream<char>::basic_ofstream(std::__cxx11::string&)’

**Comment by welbeckzhou** [comment]
> When Compile c++ files to .so for python use:
> 
> python setup.py build_ext -i
> the error occurs.
> 
> I use python 3.6, and the default gcc version in my anaconda env is 7.3.0

**Comment by zhuhaozh** [comment]
I solved this by modified mesh_core.cpp (line 349) 
from
```
    ofstream obj_file(filename);
```

to 

```
    ofstream obj_file(filename.c_str());
```

reference: [link](https://stackoverflow.com/questions/35045781/no-matching-function-for-call-to-stdbasic-ofstreamchar-stdchar-traitscha)

**Comment by gangeqian** [comment]
this bug always exits in project, 
I also solved this issue by modifiing 
ofstream obj_file(filename.c_str());
