### ISSUE TITLE
The Problem of Generating UV Map

### ISSUE THREAD

**Issue by yqwu94** [YadiraF/face3d#58]
When I run 6_generate_image_map.py script, I found that there are difference between my result and author's result on uv_coords.jpg.

uv_coords = face3d.morphable_model.load.load_uv_coords('Data/BFM/Out/BFM_UV.mat') 
uv_coords_image = mesh.render.render_colors(image_vertices, triangles, attribute, h, w, c=2) 
uv_coords_image = np.concatenate((np.zeros((h, w, 1)), uv_coords_image), 2)
io.imsave('{}/uv_coords.jpg'.format(save_folder), np.squeeze(uv_coords_image))

![color](https://user-images.githubusercontent.com/32511789/65517217-ecff3900-df14-11e9-84c3-83a680fe81e7.jpg)
![depth](https://user-images.githubusercontent.com/32511789/65517243-f5577400-df14-11e9-83d6-a65886f0a52a.jpg)
![uv_coords](https://user-images.githubusercontent.com/32511789/65517255-fa1c2800-df14-11e9-8e04-7bd7a9c83ead.jpg)

I think that there are some difference between my BFM_UV.mat and author's BFM_UV.mat. Is there anyone who can provide a file A that can be used correctly?

**Comment by Bhuvan-21** [comment]
Hi, were you able to identify the reason for this type of UV Map?
I am facing a similar issue myself.
