### ISSUE TITLE
Links to BFM data are expired

### ISSUE THREAD

**Issue by olalium** [YadiraF/face3d#67]
[Download links](http://www.cbsr.ia.ac.cn/users/xiangyuzhu/projects/HPEN/main.htm) for the [HPEN](http://www.cbsr.ia.ac.cn/users/xiangyuzhu/projects/HPEN/Code/CVPR2015_HPEN.zip) and [3DMM Fitting](http://www.cbsr.ia.ac.cn/users/xiangyuzhu/projects/HPEN/Code/3DMMFitting.zip) code does not work. Are these downloads available somewhere else?

**Comment by jjandnn** [comment]
BFM：https://drive.google.com/open?id=1Bl21HtvjHNFguEy_i1W5g0QOL8ybPzxw，
我虽然在这里提供了链接，但还是希望小伙伴们，自己生成一遍，对大家理解原理有好处！
作者其实所有的‘read me‘ 里已经明确告知了生成方法，虽然上面问题中两个文件缺失，但在HPEN剩下的连接中，提供了FaceProfilingRelease_v1.1。这里补全你们所有需要的文件，同时，运行generate.m时，注释掉5,6两步，就直接生成BFM了。
祝大家顺利，能够有新的技术突破！
（以下英语为上面文字的机翻，The following English is a machine translation of the above text）
Even though I have provided the link here, I still hope that my friends can generate the link themselves, which is helpful for everyone to understand the principle!

In fact, the author has clearly informed the generation method in all the "readme". Despite the lack of two files in the above question, FaceProfilingRelease_v1.1 is provided in the remaining connections of HPEN. Complete all the files you need here. Also, when you run generate.m, comment out steps 5 and 6, and then generate the BFM directly.

I wish you all success and new breakthroughs in technology!

**Comment by abelghazinyan** [comment]
@jjandnn Your link is expired, can you upload one more time?
