### ISSUE TITLE
face3d/morphable_model/fit.py 

### ISSUE THREAD

**Issue by diggle1** [YadiraF/face3d#72]
Excuse me, why are the indexes of landmark points timed by 3?
![image](https://user-images.githubusercontent.com/38290717/85649952-f5b8b180-b6d6-11ea-893a-107090c34cc9.png)

**Comment by csyuhao** [comment]
`X_ind` means the index of 68-landmarks in human face, which can be described $(x, y, z)$. In `ShapeMU`, `ShapePC`, `texMU` and `texPC`, for example, there are two points P_1(x_1, y_1, y_2) and P_2(x_2, y_2, z_2), which are stored as x_1, y_1, z_1, x_2, y_2, z_2. If the index of a landmark point is `3`, in `ShapeMU`, the value of this point is stored in `9, 10, 11`. So in this code, the author first copies the index three times, multiply 3, and then adds `(0, 1, 2)` in order.

**Comment by diggle1** [comment]
Many thanks

**Comment by xiaoshudi** [comment]
Many thanks
