### ISSUE TITLE
3dmm fitting result does not look like the input image

### ISSUE THREAD

**Issue by zengxianyu** [YadiraF/face3d#73]
The input image with landmarks:
![bfm](https://user-images.githubusercontent.com/11615174/89974046-9158ae00-dc94-11ea-830a-e311793cba10.png)

and the result is not good. 
<img width="450" alt="Screen Shot 2020-08-12 at 12 08 22 PM" src="https://user-images.githubusercontent.com/11615174/89974055-987fbc00-dc94-11ea-9af5-c2fda93d7cbe.png">
<img width="525" alt="Screen Shot 2020-08-12 at 12 08 11 PM" src="https://user-images.githubusercontent.com/11615174/89974056-9ae21600-dc94-11ea-820c-8e905d16deec.png">

Is this caused by fitting the 3dmm model using 2d landmark or BFM not working well for Asian faces?

**Comment by sublimationAC** [comment]
I suppose the texture on the ears is from the color of the wall, based on the image.

**Comment by zengxianyu** [comment]
> I suppose the texture on the ears is from the color of the wall, based on the image.

The color is copied from the image and basically makes sense, but the shape is not correct (e.g., the nose and mouth

**Comment by sublimationAC** [comment]
Ok, I get what u mean now. 
Ur inference is correct. Due to the sparse landmark constrain, we cannot fit the shape of the nose.
However, I guess u can try to use texture to help the algorithm fit it.

**Comment by sublimationAC** [comment]
> > I suppose the texture on the ears is from the color of the wall, based on the image.
> 
> The color is copied from the image and basically makes sense, but the shape is not correct (e.g., the nose and mouth

Ok, I get what u mean now.
Ur inference is correct. Due to the sparse landmark constrain, we cannot fit the shape of the nose.
However, I guess u can try to use texture to help the algorithm fit it.

**Comment by essebbaninaim** [comment]
Hi,

Sorry to bother you but im new with python tools.

I try to generate a 3DMM from a picture.

Can you pls share the code u used to  make the render.
That will help me a lot !

Thanks in advance !

**Comment by fisakhan** [comment]
@zengxianyu  How did you do that? How can I input my 2D image and generate its 3D model?

**Comment by zengxianyu** [comment]
https://github.com/ascust/3DMM-Fitting-Pytorch
this repo works better for fitting to 2D images

**Comment by fisakhan** [comment]
> https://github.com/ascust/3DMM-Fitting-Pytorch
> this repo works better for fitting to 2D images

@zengxianyu Thank you.

**Comment by Zenway-Wong** [comment]
Hello, could you please share how you got the final 3D model from image? How did you get the texture, expression and shape parameter for BFM.

I go through the code and just find the function to fit the 68 key points (not image!) and return expression and shape parameter.
