### ISSUE TITLE
import mesh_core_cython error

### ISSUE THREAD

**Issue by yyssmm** [YadiraF/face3d#8]
Hi,
I meet an error like this:
from .cython import mesh_core_cython
ImportError: cannot import name 'mesh_core_cython'

how can I solve it?Thanks

**Comment by wqnow** [comment]
Please install face3d first refering to readme.md file.
But I encountered a error when install：
“
\face3d\mesh\cython>python setup.py build_ext -i
running build_ext
skipping 'mesh_core_cython.cpp' Cython extension (up-to-date)
building 'mesh_core_cython' extension
error: Unable to find vcvarsall.bat
”

**Comment by danindiana** [comment]
If you are sure you have installed cython AND you are running python 3.X from a virtualenv then try: 

$pip3 install --upgrade cython

Then compile c++ files to .so for python use via:

cd face3d/mesh/cython
python setup.py build_ext -i 

![image](https://user-images.githubusercontent.com/3030588/52509019-34ba9580-2bbc-11e9-9e7c-18791bf314da.png)

**Comment by mrizwan18** [comment]
> Please install face3d first refering to readme.md file.
> But I encountered a error when install：
> “
> \face3d\mesh\cython>python setup.py build_ext -i
> running build_ext
> skipping 'mesh_core_cython.cpp' Cython extension (up-to-date)
> building 'mesh_core_cython' extension
> error: Unable to find vcvarsall.bat
> ”

How did you solve it?

**Comment by jluo96** [comment]
https://devblogs.microsoft.com/python/unable-to-find-vcvarsall-bat/

**Comment by jordanfranklin1** [comment]
Sorry if this is a stupid question, but I am having trouble with installing this module and received this error message:

ModuleNotFoundError: No module named 'mesh_core_cython'

How to install it on Ubuntu command line? I also have pip installed.

**Comment by redwankarimsony** [comment]
> 

This is the only working solution. Thanks.

**Comment by GCSlwl** [comment]
I encountered a error :

running build_ext
skipping 'mesh_core_cython.cpp' Cython extension (up-to-date)
building 'mesh_core_cython' extension
error: Unable to find vcvarsall.bat

when I running the order :
python setup.py build_ext -i

How did I solve it

**Comment by yuanliangxie** [comment]
you can see the blog: https://blog.csdn.net/dihunyi6451/article/details/101603058?spm=1001.2101.3001.6650.1&utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-1-101603058-blog-121116420.pc_relevant_recovery_v2&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-1-101603058-blog-121116420.pc_relevant_recovery_v2&utm_relevant_index=2

It has solved my problem!
